version: "3.8"

services:
  location-service:
    build: .
    container_name: uptime-location-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - env.production
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
